/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quebracabeca;

import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author IFPR
 */
public class FormHardLetter extends javax.swing.JFrame {

    /**
     * Creates new form FormHardLetter
     */
    public FormHardLetter() {
        initComponents();
        timer = new Timer();
        timerTask = new Cronometro();
        timer.scheduleAtFixedRate(timerTask, 0, 1);

    }

    int newX;
    int newY;
    private TimerTask timerTask;
    private Timer timer;
    RankingDAO rankingDao = new RankingDAO();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelT13 = new javax.swing.JLabel();
        labelT4 = new javax.swing.JLabel();
        labelT9 = new javax.swing.JLabel();
        labelT5 = new javax.swing.JLabel();
        jEmpty = new javax.swing.JLabel();
        labelT6 = new javax.swing.JLabel();
        labelT7 = new javax.swing.JLabel();
        labelT8 = new javax.swing.JLabel();
        labelT12 = new javax.swing.JLabel();
        labelT11 = new javax.swing.JLabel();
        labelT10 = new javax.swing.JLabel();
        labelT1 = new javax.swing.JLabel();
        labelT14 = new javax.swing.JLabel();
        labelT2 = new javax.swing.JLabel();
        labelT15 = new javax.swing.JLabel();
        labelT3 = new javax.swing.JLabel();
        labelT17 = new javax.swing.JLabel();
        labelT18 = new javax.swing.JLabel();
        labelT16 = new javax.swing.JLabel();
        labelT20 = new javax.swing.JLabel();
        labelT21 = new javax.swing.JLabel();
        labelT22 = new javax.swing.JLabel();
        labelT23 = new javax.swing.JLabel();
        labelT24 = new javax.swing.JLabel();
        labelT19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelSegundos = new java.awt.Label();
        labelMiliseg = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        labelMinutos = new java.awt.Label();
        sairBT = new javax.swing.JButton();
        refazerBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelT13.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT13.setText("F");
        labelT13.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT13MouseClicked(evt);
            }
        });

        labelT4.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT4.setText("K");
        labelT4.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT4MouseClicked(evt);
            }
        });

        labelT9.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT9.setText("E");
        labelT9.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT9MouseClicked(evt);
            }
        });

        labelT5.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT5.setText("N");
        labelT5.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT5MouseClicked(evt);
            }
        });

        jEmpty.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        labelT6.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT6.setText("A");
        labelT6.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT6MouseClicked(evt);
            }
        });

        labelT7.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT7.setText("M");
        labelT7.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT7MouseClicked(evt);
            }
        });

        labelT8.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT8.setText("O");
        labelT8.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT8MouseClicked(evt);
            }
        });

        labelT12.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT12.setText("G");
        labelT12.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT12MouseClicked(evt);
            }
        });

        labelT11.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT11.setText("H");
        labelT11.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT11MouseClicked(evt);
            }
        });

        labelT10.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT10.setText("D");
        labelT10.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT10MouseClicked(evt);
            }
        });

        labelT1.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT1.setText("B");
        labelT1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT1MouseClicked(evt);
            }
        });

        labelT14.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT14.setText("L");
        labelT14.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT14MouseClicked(evt);
            }
        });

        labelT2.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT2.setText("C");
        labelT2.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT2MouseClicked(evt);
            }
        });

        labelT15.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT15.setText("I");
        labelT15.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT15MouseClicked(evt);
            }
        });

        labelT3.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT3.setText("J");
        labelT3.setToolTipText("");
        labelT3.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT3MouseClicked(evt);
            }
        });

        labelT17.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT17.setText("T");
        labelT17.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT17MouseClicked(evt);
            }
        });

        labelT18.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT18.setText("U");
        labelT18.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT18MouseClicked(evt);
            }
        });

        labelT16.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT16.setText("W");
        labelT16.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT16MouseClicked(evt);
            }
        });

        labelT20.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT20.setText("P");
        labelT20.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT20MouseClicked(evt);
            }
        });

        labelT21.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT21.setText("X");
        labelT21.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT21MouseClicked(evt);
            }
        });

        labelT22.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT22.setText("S");
        labelT22.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT22MouseClicked(evt);
            }
        });

        labelT23.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT23.setText("R");
        labelT23.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT23MouseClicked(evt);
            }
        });

        labelT24.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT24.setText("Q");
        labelT24.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT24MouseClicked(evt);
            }
        });

        labelT19.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelT19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelT19.setText("V");
        labelT19.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        labelT19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT19MouseClicked(evt);
            }
        });

        labelSegundos.setAlignment(1);
        labelSegundos.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        labelSegundos.setName(""); // NOI18N
        labelSegundos.setText("00");

        labelMiliseg.setAlignment(1);
        labelMiliseg.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelMiliseg.setText("000");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText(":");

        labelMinutos.setAlignment(1);
        labelMinutos.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        labelMinutos.setName(""); // NOI18N
        labelMinutos.setText("00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMinutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSegundos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMiliseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelMiliseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sairBT.setFont(new java.awt.Font("Press Start 2P", 0, 11)); // NOI18N
        sairBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontes/Programming-Delete-Sign-icon.png"))); // NOI18N
        sairBT.setText("Sair");
        sairBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBTActionPerformed(evt);
            }
        });

        refazerBT.setFont(new java.awt.Font("Press Start 2P", 0, 11)); // NOI18N
        refazerBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontes/Very-Basic-Reload-icon.png"))); // NOI18N
        refazerBT.setText("Restart");
        refazerBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refazerBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelT5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(labelT6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(labelT7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(labelT8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelT13, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelT9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelT17, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelT10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelT18, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelT14, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sairBT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelT19, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(labelT20, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelT11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(labelT12, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelT15, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(labelT24, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelT22, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelT23, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelT16, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelT1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(labelT2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(labelT3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(labelT4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(labelT21, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233)
                        .addComponent(refazerBT)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelT13, labelT17, labelT18, labelT19, labelT20});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelT15, labelT16, labelT24});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelT21, labelT4});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelT22, labelT8});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelT12, labelT23});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {refazerBT, sairBT});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelT1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelT2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelT3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelT4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelT21, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelT5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelT6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelT7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelT8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelT22, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelT9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelT10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelT11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelT23, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelT12, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelT13, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelT14, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelT15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelT24, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelT16, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelT17, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelT18, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelT19, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelT20, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sairBT)
                            .addComponent(refazerBT))
                        .addGap(25, 25, 25))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelT21, labelT4});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelT13, labelT17, labelT18, labelT19, labelT20});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelT15, labelT16, labelT24});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelT22, labelT8});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelT12, labelT23});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {refazerBT, sairBT});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void setTextoCronometroSegundos(String texto) {
        labelSegundos.setText(texto);
    }

    public static void setTextoCronometroMinutos(String texto) {
        labelMinutos.setText(texto);
    }

    public static void setTextoCronometroMilisegundos(String texto) {
        labelMiliseg.setText(texto);
    }

    public String getPos(JLabel label) {
        String pos = label.getX() + "," + label.getY();
        return pos;
    }

    private void labelT13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT13MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT13.getX() + 125 + "," + labelT13.getY())) {
            newX = labelT13.getX() + 125;
            jEmpty.setBounds(labelT13.getX(), labelT13.getY(), 125, 125);
            labelT13.setBounds(newX, labelT13.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT13.getX() - 125 + "," + labelT13.getY())) {
            newX = labelT13.getX() - 125;
            jEmpty.setBounds(labelT13.getX(), labelT13.getY(), 125, 125);
            labelT13.setBounds(newX, labelT13.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT13.getX() + "," + (labelT13.getY() + 125))) {
            newY = labelT13.getY() + 125;
            jEmpty.setBounds(labelT13.getX(), labelT13.getY(), 125, 125);
            labelT13.setBounds(labelT13.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT13.getX() + "," + (labelT13.getY() - 125))) {
            newY = labelT13.getY() - 125;
            jEmpty.setBounds(labelT13.getX(), labelT13.getY(), 125, 125);
            labelT13.setBounds(labelT13.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT13MouseClicked

    private void labelT4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT4MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT4.getX() + 125 + "," + labelT4.getY())) {
            newX = labelT4.getX() + 125;
            jEmpty.setBounds(labelT4.getX(), labelT4.getY(), 125, 125);
            labelT4.setBounds(newX, labelT4.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT4.getX() - 125 + "," + labelT4.getY())) {
            newX = labelT4.getX() - 125;
            jEmpty.setBounds(labelT4.getX(), labelT4.getY(), 125, 125);
            labelT4.setBounds(newX, labelT4.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT4.getX() + "," + (labelT4.getY() + 125))) {
            newY = labelT4.getY() + 125;
            jEmpty.setBounds(labelT4.getX(), labelT4.getY(), 125, 125);
            labelT4.setBounds(labelT4.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT4.getX() + "," + (labelT4.getY() - 125))) {
            newY = labelT4.getY() - 125;
            jEmpty.setBounds(labelT4.getX(), labelT4.getY(), 125, 125);
            labelT4.setBounds(labelT4.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT4MouseClicked

    private void labelT9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT9MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT9.getX() + 125 + "," + labelT9.getY())) {
            newX = labelT9.getX() + 125;
            jEmpty.setBounds(labelT9.getX(), labelT9.getY(), 125, 125);
            labelT9.setBounds(newX, labelT9.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT9.getX() - 125 + "," + labelT9.getY())) {
            newX = labelT9.getX() - 125;
            jEmpty.setBounds(labelT9.getX(), labelT9.getY(), 125, 125);
            labelT9.setBounds(newX, labelT9.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT9.getX() + "," + (labelT9.getY() + 125))) {
            newY = labelT9.getY() + 125;
            jEmpty.setBounds(labelT9.getX(), labelT9.getY(), 125, 125);
            labelT9.setBounds(labelT9.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT9.getX() + "," + (labelT9.getY() - 125))) {
            newY = labelT9.getY() - 125;
            jEmpty.setBounds(labelT9.getX(), labelT9.getY(), 125, 125);
            labelT9.setBounds(labelT9.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT9MouseClicked

    private void labelT5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT5MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT5.getX() + 125 + "," + labelT5.getY())) {
            newX = labelT5.getX() + 125;
            jEmpty.setBounds(labelT5.getX(), labelT5.getY(), 125, 125);
            labelT5.setBounds(newX, labelT5.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT5.getX() - 125 + "," + labelT5.getY())) {
            newX = labelT5.getX() - 125;
            jEmpty.setBounds(labelT5.getX(), labelT5.getY(), 125, 125);
            labelT5.setBounds(newX, labelT5.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT5.getX() + "," + (labelT5.getY() - 125))) {
            newY = labelT5.getY() - 125;
            jEmpty.setBounds(labelT5.getX(), labelT5.getY(), 125, 125);
            labelT5.setBounds(labelT5.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT5.getX() + "," + (labelT5.getY() + 125))) {
            newY = labelT5.getY() + 125;
            jEmpty.setBounds(labelT5.getX(), labelT5.getY(), 125, 125);
            labelT5.setBounds(labelT5.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT5MouseClicked

    private void labelT6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT6MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT6.getX() + 125 + "," + labelT6.getY())) {
            newX = labelT6.getX() + 125;
            jEmpty.setBounds(labelT6.getX(), labelT6.getY(), 125, 125);
            labelT6.setBounds(newX, labelT6.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT6.getX() - 125 + "," + labelT6.getY())) {
            newX = labelT6.getX() - 125;
            jEmpty.setBounds(labelT6.getX(), labelT6.getY(), 125, 125);
            labelT6.setBounds(newX, labelT6.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT6.getX() + "," + (labelT6.getY() + 125))) {
            newY = labelT6.getY() + 125;
            jEmpty.setBounds(labelT6.getX(), labelT6.getY(), 125, 125);
            labelT6.setBounds(labelT6.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT6.getX() + "," + (labelT6.getY() - 125))) {
            newY = labelT6.getY() - 125;
            jEmpty.setBounds(labelT6.getX(), labelT6.getY(), 125, 125);
            labelT6.setBounds(labelT6.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT6MouseClicked

    private void labelT7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT7MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT7.getX() + 125 + "," + labelT7.getY())) {
            newX = labelT7.getX() + 125;
            jEmpty.setBounds(labelT7.getX(), labelT7.getY(), 125, 125);
            labelT7.setBounds(newX, labelT7.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT7.getX() - 125 + "," + labelT7.getY())) {
            newX = labelT7.getX() - 125;
            jEmpty.setBounds(labelT7.getX(), labelT7.getY(), 125, 125);
            labelT7.setBounds(newX, labelT7.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT7.getX() + "," + (labelT7.getY() + 125))) {
            newY = labelT7.getY() + 125;
            jEmpty.setBounds(labelT7.getX(), labelT7.getY(), 125, 125);
            labelT7.setBounds(labelT7.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT7.getX() + "," + (labelT7.getY() - 125))) {
            newY = labelT7.getY() - 125;
            jEmpty.setBounds(labelT7.getX(), labelT7.getY(), 125, 125);
            labelT7.setBounds(labelT7.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT7MouseClicked

    private void labelT8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT8MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT8.getX() + 125 + "," + labelT8.getY())) {
            newX = labelT8.getX() + 125;
            jEmpty.setBounds(labelT8.getX(), labelT8.getY(), 125, 125);
            labelT8.setBounds(newX, labelT8.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT8.getX() - 125 + "," + labelT8.getY())) {
            newX = labelT8.getX() - 125;
            jEmpty.setBounds(labelT8.getX(), labelT8.getY(), 125, 125);
            labelT8.setBounds(newX, labelT8.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT8.getX() + "," + (labelT8.getY() + 125))) {
            newY = labelT8.getY() + 125;
            jEmpty.setBounds(labelT8.getX(), labelT8.getY(), 125, 125);
            labelT8.setBounds(labelT8.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT8.getX() + "," + (labelT8.getY() - 125))) {
            newY = labelT8.getY() - 125;
            jEmpty.setBounds(labelT8.getX(), labelT8.getY(), 125, 125);
            labelT8.setBounds(labelT8.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT8MouseClicked

    private void labelT12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT12MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT12.getX() + 125 + "," + labelT12.getY())) {
            newX = labelT12.getX() + 125;
            jEmpty.setBounds(labelT12.getX(), labelT12.getY(), 125, 125);
            labelT12.setBounds(newX, labelT12.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT12.getX() - 125 + "," + labelT12.getY())) {
            newX = labelT12.getX() - 125;
            jEmpty.setBounds(labelT12.getX(), labelT12.getY(), 125, 125);
            labelT12.setBounds(newX, labelT12.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT12.getX() + "," + (labelT12.getY() + 125))) {
            newY = labelT12.getY() + 125;
            jEmpty.setBounds(labelT12.getX(), labelT12.getY(), 125, 125);
            labelT12.setBounds(labelT12.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT12.getX() + "," + (labelT12.getY() - 125))) {
            newY = labelT12.getY() - 125;
            jEmpty.setBounds(labelT12.getX(), labelT12.getY(), 125, 125);
            labelT12.setBounds(labelT12.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT12MouseClicked

    private void labelT11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT11MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT11.getX() + 125 + "," + labelT11.getY())) {
            newX = labelT11.getX() + 125;
            jEmpty.setBounds(labelT11.getX(), labelT11.getY(), 125, 125);
            labelT11.setBounds(newX, labelT11.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT11.getX() - 125 + "," + labelT11.getY())) {
            newX = labelT11.getX() - 125;
            jEmpty.setBounds(labelT11.getX(), labelT11.getY(), 125, 125);
            labelT11.setBounds(newX, labelT11.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT11.getX() + "," + (labelT11.getY() + 125))) {
            newY = labelT11.getY() + 125;
            jEmpty.setBounds(labelT11.getX(), labelT11.getY(), 125, 125);
            labelT11.setBounds(labelT11.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT11.getX() + "," + (labelT11.getY() - 125))) {
            newY = labelT11.getY() - 125;
            jEmpty.setBounds(labelT11.getX(), labelT11.getY(), 125, 125);
            labelT11.setBounds(labelT11.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT11MouseClicked

    private void labelT10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT10MouseClicked
        //direita empty
        if (getPos(jEmpty).equals(labelT10.getX() + 125 + "," + labelT10.getY())) {
            newX = labelT10.getX() + 125;
            jEmpty.setBounds(labelT10.getX(), labelT10.getY(), 125, 125);
            labelT10.setBounds(newX, labelT10.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT10.getX() - 125 + "," + labelT10.getY())) {
            newX = labelT10.getX() - 125;
            jEmpty.setBounds(labelT10.getX(), labelT10.getY(), 125, 125);
            labelT10.setBounds(newX, labelT10.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT10.getX() + "," + (labelT10.getY() + 125))) {
            newY = labelT10.getY() + 125;
            jEmpty.setBounds(labelT10.getX(), labelT10.getY(), 125, 125);
            labelT10.setBounds(labelT10.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT10.getX() + "," + (labelT10.getY() - 125))) {
            newY = labelT10.getY() - 125;
            jEmpty.setBounds(labelT10.getX(), labelT10.getY(), 125, 125);
            labelT10.setBounds(labelT10.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT10MouseClicked

    private void labelT1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT1MouseClicked
        //direita empty

        if (getPos(jEmpty).equals(labelT1.getX() + 125 + "," + labelT1.getY())) {
            newX = labelT1.getX() + 125;
            jEmpty.setBounds(labelT1.getX(), labelT1.getY(), 125, 125);
            labelT1.setBounds(newX, labelT1.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT1.getX() - 125 + "," + labelT1.getY())) {
            newX = labelT1.getX() - 125;
            jEmpty.setBounds(labelT1.getX(), labelT1.getY(), 125, 125);
            labelT1.setBounds(newX, labelT1.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT1.getX() + "," + (labelT1.getY() + 125))) {
            newY = labelT1.getY() + 125;
            jEmpty.setBounds(labelT1.getX(), labelT1.getY(), 125, 125);
            labelT1.setBounds(labelT1.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT1.getX() + "," + (labelT1.getY() - 125))) {
            newY = labelT1.getY() - 125;
            jEmpty.setBounds(labelT1.getX(), labelT1.getY(), 125, 125);
            labelT1.setBounds(labelT1.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT1MouseClicked

    private void labelT14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT14MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT14.getX() + 125 + "," + labelT14.getY())) {
            newX = labelT14.getX() + 125;
            jEmpty.setBounds(labelT14.getX(), labelT14.getY(), 125, 125);
            labelT14.setBounds(newX, labelT14.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT14.getX() - 125 + "," + labelT14.getY())) {
            newX = labelT14.getX() - 125;
            jEmpty.setBounds(labelT14.getX(), labelT14.getY(), 125, 125);
            labelT14.setBounds(newX, labelT14.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT14.getX() + "," + (labelT14.getY() + 125))) {
            newY = labelT14.getY() + 125;
            jEmpty.setBounds(labelT14.getX(), labelT14.getY(), 125, 125);
            labelT14.setBounds(labelT14.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT14.getX() + "," + (labelT14.getY() - 125))) {
            newY = labelT14.getY() - 125;
            jEmpty.setBounds(labelT14.getX(), labelT14.getY(), 125, 125);
            labelT14.setBounds(labelT14.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT14MouseClicked

    private void labelT2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT2MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT2.getX() + 125 + "," + labelT2.getY())) {
            newX = labelT2.getX() + 125;
            jEmpty.setBounds(labelT2.getX(), labelT2.getY(), 125, 125);
            labelT2.setBounds(newX, labelT2.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT2.getX() - 125 + "," + labelT2.getY())) {
            newX = labelT2.getX() - 125;
            jEmpty.setBounds(labelT2.getX(), labelT2.getY(), 125, 125);
            labelT2.setBounds(newX, labelT2.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT2.getX() + "," + (labelT2.getY() + 125))) {
            newY = labelT2.getY() + 125;
            jEmpty.setBounds(labelT2.getX(), labelT2.getY(), 125, 125);
            labelT2.setBounds(labelT2.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT2.getX() + "," + (labelT2.getY() - 125))) {
            newY = labelT2.getY() - 125;
            jEmpty.setBounds(labelT2.getX(), labelT2.getY(), 125, 125);
            labelT2.setBounds(labelT2.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT2MouseClicked

    private void labelT15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT15MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT15.getX() + 125 + "," + labelT15.getY())) {
            newX = labelT15.getX() + 125;
            jEmpty.setBounds(labelT15.getX(), labelT15.getY(), 125, 125);
            labelT15.setBounds(newX, labelT15.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT15.getX() - 125 + "," + labelT15.getY())) {
            newX = labelT15.getX() - 125;
            jEmpty.setBounds(labelT15.getX(), labelT15.getY(), 125, 125);
            labelT15.setBounds(newX, labelT15.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT15.getX() + "," + (labelT15.getY() + 125))) {
            newY = labelT15.getY() + 125;
            jEmpty.setBounds(labelT15.getX(), labelT15.getY(), 125, 125);
            labelT15.setBounds(labelT15.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT15.getX() + "," + (labelT15.getY() - 125))) {
            newY = labelT15.getY() - 125;
            jEmpty.setBounds(labelT15.getX(), labelT15.getY(), 125, 125);
            labelT15.setBounds(labelT15.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT15MouseClicked

    private void labelT3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT3MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT3.getX() + 125 + "," + labelT3.getY())) {
            newX = labelT3.getX() + 125;
            jEmpty.setBounds(labelT3.getX(), labelT3.getY(), 125, 125);
            labelT3.setBounds(newX, labelT3.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT3.getX() - 125 + "," + labelT3.getY())) {
            newX = labelT3.getX() - 125;
            jEmpty.setBounds(labelT3.getX(), labelT3.getY(), 125, 125);
            labelT3.setBounds(newX, labelT3.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT3.getX() + "," + (labelT3.getY() + 125))) {
            newY = labelT3.getY() + 125;
            jEmpty.setBounds(labelT3.getX(), labelT3.getY(), 125, 125);
            labelT3.setBounds(labelT3.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT3.getX() + "," + (labelT3.getY() - 125))) {
            newY = labelT3.getY() - 125;
            jEmpty.setBounds(labelT3.getX(), labelT3.getY(), 125, 125);
            labelT3.setBounds(labelT3.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT3MouseClicked

    private void labelT17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT17MouseClicked
        //direita empty
        if (getPos(jEmpty).equals(labelT17.getX() + 125 + "," + labelT17.getY())) {
            newX = labelT17.getX() + 125;
            jEmpty.setBounds(labelT17.getX(), labelT17.getY(), 125, 125);
            labelT17.setBounds(newX, labelT17.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT17.getX() - 125 + "," + labelT17.getY())) {
            newX = labelT17.getX() - 125;
            jEmpty.setBounds(labelT17.getX(), labelT17.getY(), 125, 125);
            labelT17.setBounds(newX, labelT17.getY(), 125, 125);
        } //cima empty
        else if (getPos(jEmpty).equals(labelT17.getX() + "," + (labelT17.getY() - 125))) {
            newY = labelT17.getY() - 125;
            jEmpty.setBounds(labelT17.getX(), labelT17.getY(), 125, 125);
            labelT17.setBounds(labelT17.getX(), newY, 125, 125);
        } //baixo empty
        else if (getPos(jEmpty).equals(labelT17.getX() + "," + (labelT17.getY() + 125))) {
            newY = labelT17.getY() + 125;
            jEmpty.setBounds(labelT17.getX(), labelT17.getY(), 125, 125);
            labelT17.setBounds(labelT17.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT17MouseClicked

    private void labelT20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT20MouseClicked
        //direita empty
        if (getPos(jEmpty).equals(labelT20.getX() + 125 + "," + labelT20.getY())) {
            newX = labelT20.getX() + 125;
            jEmpty.setBounds(labelT20.getX(), labelT20.getY(), 125, 125);
            labelT20.setBounds(newX, labelT20.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT20.getX() - 125 + "," + labelT20.getY())) {
            newX = labelT20.getX() - 125;
            jEmpty.setBounds(labelT20.getX(), labelT20.getY(), 125, 125);
            labelT20.setBounds(newX, labelT20.getY(), 125, 125);
        } //cima empty
        else if (getPos(jEmpty).equals(labelT20.getX() + "," + (labelT20.getY() + 125))) {
            newY = labelT20.getY() + 125;
            jEmpty.setBounds(labelT20.getX(), labelT20.getY(), 125, 125);
            labelT20.setBounds(labelT20.getX(), newY, 125, 125);
        } //baixoEmpty
        else if (getPos(jEmpty).equals(labelT20.getX() + "," + (labelT20.getY() - 125))) {
            newY = labelT20.getY() - 125;
            jEmpty.setBounds(labelT20.getX(), labelT20.getY(), 125, 125);
            labelT20.setBounds(labelT20.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }

    }//GEN-LAST:event_labelT20MouseClicked

    private void labelT16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT16MouseClicked
        //direita limpo
        if (getPos(jEmpty).equals((labelT16.getX() + 125) + "," + labelT16.getY())) {
            newX = labelT16.getX() + 125;
            jEmpty.setBounds(labelT16.getX(), labelT16.getY(), 125, 125);
            labelT16.setBounds(newX, labelT16.getY(), 125, 125);
        } //esquerda limpo
        else if (getPos(jEmpty).equals(labelT16.getX() - 125 + "," + labelT16.getY())) {
            newX = labelT16.getX() - 125;
            jEmpty.setBounds(labelT16.getX(), labelT16.getY(), 125, 125);
            labelT16.setBounds(newX, labelT16.getY(), 125, 125);
        } //subir limpo
        else if (getPos(jEmpty).equals(labelT16.getX() + "," + (labelT16.getY() + 125))) {
            newY = labelT16.getY() + 125;
            jEmpty.setBounds(labelT16.getX(), labelT16.getY(), 125, 125);
            labelT16.setBounds(labelT16.getX(), newY, 125, 125);
        } //baixoEmpty
        else if (getPos(jEmpty).equals(labelT16.getX() + "," + (labelT16.getY() - 125))) {
            newY = labelT16.getY() - 125;
            jEmpty.setBounds(labelT16.getX(), labelT16.getY(), 125, 125);
            labelT16.setBounds(labelT16.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }

    }//GEN-LAST:event_labelT16MouseClicked

    private void labelT24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT24MouseClicked
        //direita empty
        if (getPos(jEmpty).equals(labelT24.getX() + 125 + "," + labelT24.getY())) {
            newX = labelT24.getX() + 125;
            jEmpty.setBounds(labelT24.getX(), labelT24.getY(), 125, 125);
            labelT24.setBounds(newX, labelT24.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT24.getX() - 125 + "," + labelT24.getY())) {
            newX = labelT24.getX() - 125;
            jEmpty.setBounds(labelT24.getX(), labelT24.getY(), 125, 125);
            labelT24.setBounds(newX, labelT24.getY(), 125, 125);
        } //cima empty
        else if (getPos(jEmpty).equals(labelT24.getX() + "," + (labelT24.getY() + 125))) {
            newY = labelT24.getY() + 125;
            jEmpty.setBounds(labelT24.getX(), labelT24.getY(), 125, 125);
            labelT24.setBounds(labelT24.getX(), newY, 125, 125);
        } //baixoEmpty
        else if (getPos(jEmpty).equals(labelT24.getX() + "," + (labelT24.getY() - 125))) {
            newY = labelT24.getY() - 125;
            jEmpty.setBounds(labelT24.getX(), labelT24.getY(), 125, 125);
            labelT24.setBounds(labelT24.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }

    }//GEN-LAST:event_labelT24MouseClicked

    private void labelT23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT23MouseClicked
        //direita empty
        if (getPos(jEmpty).equals(labelT23.getX() + 125 + "," + labelT23.getY())) {
            newX = labelT23.getX() + 125;
            jEmpty.setBounds(labelT23.getX(), labelT23.getY(), 125, 125);
            labelT23.setBounds(newX, labelT23.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT23.getX() - 125 + "," + labelT23.getY())) {
            newX = labelT23.getX() - 125;
            jEmpty.setBounds(labelT23.getX(), labelT23.getY(), 125, 125);
            labelT23.setBounds(newX, labelT23.getY(), 125, 125);
        } //cima empty
        else if (getPos(jEmpty).equals(labelT23.getX() + "," + (labelT23.getY() + 125))) {
            newY = labelT23.getY() + 125;
            jEmpty.setBounds(labelT23.getX(), labelT23.getY(), 125, 125);
            labelT23.setBounds(labelT23.getX(), newY, 125, 125);
        } //baixoEmpty
        else if (getPos(jEmpty).equals(labelT23.getX() + "," + (labelT23.getY() - 125))) {
            newY = labelT23.getY() - 125;
            jEmpty.setBounds(labelT23.getX(), labelT23.getY(), 125, 125);
            labelT23.setBounds(labelT23.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT23MouseClicked

    private void labelT22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT22MouseClicked
        //direita empty
        if (getPos(jEmpty).equals(labelT22.getX() + 125 + "," + labelT22.getY())) {
            newX = labelT22.getX() + 125;
            jEmpty.setBounds(labelT22.getX(), labelT22.getY(), 125, 125);
            labelT22.setBounds(newX, labelT22.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT22.getX() - 125 + "," + labelT22.getY())) {
            newX = labelT22.getX() - 125;
            jEmpty.setBounds(labelT22.getX(), labelT22.getY(), 125, 125);
            labelT22.setBounds(newX, labelT22.getY(), 125, 125);
        } //cima empty
        else if (getPos(jEmpty).equals(labelT22.getX() + "," + (labelT22.getY() + 125))) {
            newY = labelT22.getY() + 125;
            jEmpty.setBounds(labelT22.getX(), labelT22.getY(), 125, 125);
            labelT22.setBounds(labelT22.getX(), newY, 125, 125);
        } //baixoEmpty
        else if (getPos(jEmpty).equals(labelT22.getX() + "," + (labelT22.getY() - 125))) {
            newY = labelT22.getY() - 125;
            jEmpty.setBounds(labelT22.getX(), labelT22.getY(), 125, 125);
            labelT22.setBounds(labelT22.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT22MouseClicked

    private void labelT21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT21MouseClicked
        //direita empty
        if (getPos(jEmpty).equals((labelT21.getX() + 125) + "," + labelT21.getY())) {
            newX = labelT21.getX() + 125;
            jEmpty.setBounds(labelT21.getX(), labelT21.getY(), 125, 125);
            labelT21.setBounds(newX, labelT21.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals((labelT21.getX() - 125) + "," + labelT21.getY())) {
            newX = labelT21.getX() - 125;
            jEmpty.setBounds(labelT21.getX(), labelT21.getY(), 125, 125);
            labelT21.setBounds(newX, labelT21.getY(), 125, 125);
        } //em cima empty
        else if (getPos(jEmpty).equals(labelT21.getX() + "," + (labelT21.getY() + 125))) {
            newY = labelT21.getY() + 125;
            jEmpty.setBounds(labelT21.getX(), labelT21.getY(), 125, 125);
            labelT21.setBounds(labelT21.getX(), newY, 125, 125);
        } // baixo vazio
        else if (getPos(jEmpty).equals(labelT21.getX() + "," + (labelT21.getY() - 125))) {
            newY = labelT21.getY() - 125;
            jEmpty.setBounds(labelT21.getX(), labelT21.getY(), 125, 125);
            labelT21.setBounds(labelT21.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT21MouseClicked

    private void labelT18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT18MouseClicked
        //direita empty
        if (getPos(jEmpty).equals(labelT18.getX() + 125 + "," + labelT18.getY())) {
            newX = labelT18.getX() + 125;
            jEmpty.setBounds(labelT18.getX(), labelT18.getY(), 125, 125);
            labelT18.setBounds(newX, labelT18.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT18.getX() - 125 + "," + labelT18.getY())) {
            newX = labelT18.getX() - 125;
            jEmpty.setBounds(labelT18.getX(), labelT18.getY(), 125, 125);
            labelT18.setBounds(newX, labelT18.getY(), 125, 125);
        } //cima empty
        else if (getPos(jEmpty).equals(labelT18.getX() + "," + (labelT18.getY() - 125))) {
            newY = labelT18.getY() - 125;
            jEmpty.setBounds(labelT18.getX(), labelT18.getY(), 125, 125);
            labelT18.setBounds(labelT18.getX(), newY, 125, 125);
        } //baixo empty
        else if (getPos(jEmpty).equals(labelT18.getX() + "," + (labelT18.getY() + 125))) {
            newY = labelT18.getY() + 125;
            jEmpty.setBounds(labelT18.getX(), labelT18.getY(), 125, 125);
            labelT18.setBounds(labelT18.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT18MouseClicked

    private void labelT19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT19MouseClicked
        //direita empty
        if (getPos(jEmpty).equals(labelT19.getX() + 125 + "," + labelT19.getY())) {
            newX = labelT19.getX() + 125;
            jEmpty.setBounds(labelT19.getX(), labelT19.getY(), 125, 125);
            labelT19.setBounds(newX, labelT19.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT19.getX() - 125 + "," + labelT19.getY())) {
            newX = labelT19.getX() - 125;
            jEmpty.setBounds(labelT19.getX(), labelT19.getY(), 125, 125);
            labelT19.setBounds(newX, labelT19.getY(), 125, 125);
        } //cima empty
        else if (getPos(jEmpty).equals(labelT19.getX() + "," + (labelT19.getY() - 125))) {
            newY = labelT19.getY() - 125;
            jEmpty.setBounds(labelT19.getX(), labelT19.getY(), 125, 125);
            labelT19.setBounds(labelT19.getX(), newY, 125, 125);
        } //baixo empty
        else if (getPos(jEmpty).equals(labelT19.getX() + "," + (labelT19.getY() + 125))) {
            newY = labelT19.getY() + 125;
            jEmpty.setBounds(labelT19.getX(), labelT19.getY(), 125, 125);
            labelT19.setBounds(labelT19.getX(), newY, 125, 125);
        }

        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT19MouseClicked

    private void sairBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBTActionPerformed
        dispose();
        timer.cancel();
    }//GEN-LAST:event_sairBTActionPerformed

    private void refazerBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refazerBTActionPerformed

        labelT1.setBounds(0, 0, 125, 125);
        labelT2.setBounds(125, 0, 125, 125);
        labelT3.setBounds(250, 0, 125, 125);
        labelT4.setBounds(375, 0, 125, 125);
        labelT21.setBounds(500, 0, 125, 125);

        labelT5.setBounds(0, 125, 125, 125);
        labelT6.setBounds(125, 125, 125, 125);
        labelT7.setBounds(250, 125, 125, 125);
        labelT8.setBounds(375, 125, 125, 125);
        labelT22.setBounds(500, 125, 125, 125);

        labelT9.setBounds(0, 250, 125, 125);
        labelT10.setBounds(125, 250, 125, 125);
        labelT11.setBounds(250, 250, 125, 125);
        labelT12.setBounds(375, 250, 125, 125);
        labelT23.setBounds(500, 250, 125, 125);

        labelT13.setBounds(0, 375, 125, 125);
        labelT14.setBounds(125, 375, 125, 125);
        labelT15.setBounds(250, 375, 125, 125);
        labelT24.setBounds(375, 375, 125, 125);
        labelT16.setBounds(500, 375, 125, 125);

        labelT17.setBounds(0, 500, 125, 125);
        labelT18.setBounds(125, 500, 125, 125);
        labelT19.setBounds(250, 500, 125, 125);
        labelT20.setBounds(375, 500, 125, 125);
        jEmpty.setBounds(500, 500, 125, 125);
        
        timer.cancel();
        labelMiliseg.setText("000");
        labelMinutos.setText("00");
        labelSegundos.setText("00");
            
        timer = new Timer();
        timerTask = new Cronometro();
        timer.scheduleAtFixedRate(timerTask, 0, 1);


    }//GEN-LAST:event_refazerBTActionPerformed

    public boolean winCondition() {

        if (getPos(labelT6).equals("0,0")
                && getPos(labelT1).equals("125,0")
                && getPos(labelT2).equals("250,0")
                && getPos(labelT10).equals("375,0")
                && getPos(labelT9).equals("500,0")
                && getPos(labelT13).equals("0,125")
                && getPos(labelT12).equals("125,125")
                && getPos(labelT11).equals("250,125")
                && getPos(labelT15).equals("375,125")
                && getPos(labelT3).equals("500,125")
                && getPos(labelT4).equals("0,250")
                && getPos(labelT14).equals("125,250")
                && getPos(labelT7).equals("250,250")
                && getPos(labelT5).equals("375,250")
                && getPos(labelT8).equals("500,250")
                && getPos(labelT20).equals("0,375")
                && getPos(labelT24).equals("125,375")
                && getPos(labelT23).equals("250,375")
                && getPos(labelT22).equals("375,375")
                && getPos(labelT17).equals("500,375")
                && getPos(labelT18).equals("0,500")
                && getPos(labelT19).equals("125,500")
                && getPos(labelT16).equals("250,500")
                && getPos(labelT21).equals("375,500")) {

            timer.cancel();
            rankingDao.letraHard();
            return true;
        }

        return false;
    }

    Cronometro cronometro;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jEmpty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private static java.awt.Label labelMiliseg;
    private static java.awt.Label labelMinutos;
    private static java.awt.Label labelSegundos;
    private javax.swing.JLabel labelT1;
    private javax.swing.JLabel labelT10;
    private javax.swing.JLabel labelT11;
    private javax.swing.JLabel labelT12;
    private javax.swing.JLabel labelT13;
    private javax.swing.JLabel labelT14;
    private javax.swing.JLabel labelT15;
    private javax.swing.JLabel labelT16;
    private javax.swing.JLabel labelT17;
    private javax.swing.JLabel labelT18;
    private javax.swing.JLabel labelT19;
    private javax.swing.JLabel labelT2;
    private javax.swing.JLabel labelT20;
    private javax.swing.JLabel labelT21;
    private javax.swing.JLabel labelT22;
    private javax.swing.JLabel labelT23;
    private javax.swing.JLabel labelT24;
    private javax.swing.JLabel labelT3;
    private javax.swing.JLabel labelT4;
    private javax.swing.JLabel labelT5;
    private javax.swing.JLabel labelT6;
    private javax.swing.JLabel labelT7;
    private javax.swing.JLabel labelT8;
    private javax.swing.JLabel labelT9;
    private javax.swing.JButton refazerBT;
    private javax.swing.JButton sairBT;
    // End of variables declaration//GEN-END:variables
}
