/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quebracabeca;

import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mathe
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     *
     * @param parent
     */
    public FormMenu(JFrame parent) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        painelInternoMenu2.setBackground(Color.CYAN);
        getContentPane().setBackground(Color.DARK_GRAY);

    }

    FormRanking formRanking = new FormRanking();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelInternoMenu2 = new javax.swing.JPanel();
        facilCB = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        medioCB = new javax.swing.JCheckBox();
        imagemCB = new javax.swing.JCheckBox();
        numberCB = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dificilCB = new javax.swing.JCheckBox();
        letterCB = new javax.swing.JCheckBox();
        startButton = new javax.swing.JButton();
        rankingBT = new javax.swing.JButton();
        logoutBT = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelInternoMenu2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        facilCB.setFont(new java.awt.Font("Press Start 2P", 0, 11)); // NOI18N
        facilCB.setText("Facil");
        facilCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facilCBActionPerformed(evt);
            }
        });
        facilCB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                facilCBKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Press Start 2P", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontes/Very-Basic-Puzzle-icon.png"))); // NOI18N
        jLabel1.setText(" DIFICULDADES");

        medioCB.setFont(new java.awt.Font("Press Start 2P", 0, 11)); // NOI18N
        medioCB.setText("Médio");
        medioCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medioCBActionPerformed(evt);
            }
        });
        medioCB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                medioCBKeyPressed(evt);
            }
        });

        imagemCB.setFont(new java.awt.Font("Press Start 2P", 0, 11)); // NOI18N
        imagemCB.setText("Imagem");
        imagemCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagemCBActionPerformed(evt);
            }
        });
        imagemCB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                imagemCBKeyPressed(evt);
            }
        });

        numberCB.setFont(new java.awt.Font("Press Start 2P", 0, 11)); // NOI18N
        numberCB.setText("Numeros");
        numberCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberCBActionPerformed(evt);
            }
        });
        numberCB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numberCBKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Press Start 2P", 0, 11)); // NOI18N
        jLabel2.setText("TIPO:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontes/Very-Basic-Puzzle-icon.png"))); // NOI18N

        dificilCB.setFont(new java.awt.Font("Press Start 2P", 0, 11)); // NOI18N
        dificilCB.setText("Dificil");
        dificilCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dificilCBActionPerformed(evt);
            }
        });
        dificilCB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dificilCBKeyPressed(evt);
            }
        });

        letterCB.setFont(new java.awt.Font("Press Start 2P", 0, 11)); // NOI18N
        letterCB.setText("Letras");
        letterCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterCBActionPerformed(evt);
            }
        });
        letterCB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                letterCBKeyPressed(evt);
            }
        });

        startButton.setFont(new java.awt.Font("Press Start 2P", 1, 14)); // NOI18N
        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        rankingBT.setFont(new java.awt.Font("Press Start 2P", 0, 11)); // NOI18N
        rankingBT.setText("Ranking");
        rankingBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankingBTActionPerformed(evt);
            }
        });

        logoutBT.setFont(new java.awt.Font("Press Start 2P", 0, 11)); // NOI18N
        logoutBT.setText("Logout");
        logoutBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Press Start 2P", 0, 11)); // NOI18N
        jLabel4.setText("Dificuldade:");

        javax.swing.GroupLayout painelInternoMenu2Layout = new javax.swing.GroupLayout(painelInternoMenu2);
        painelInternoMenu2.setLayout(painelInternoMenu2Layout);
        painelInternoMenu2Layout.setHorizontalGroup(
            painelInternoMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInternoMenu2Layout.createSequentialGroup()
                .addGroup(painelInternoMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelInternoMenu2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelInternoMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letterCB)
                            .addGroup(painelInternoMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(numberCB)
                                .addComponent(imagemCB)))
                        .addGap(27, 27, 27))
                    .addGroup(painelInternoMenu2Layout.createSequentialGroup()
                        .addGroup(painelInternoMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelInternoMenu2Layout.createSequentialGroup()
                                .addGroup(painelInternoMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelInternoMenu2Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel4))
                                    .addGroup(painelInternoMenu2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(rankingBT)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(startButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInternoMenu2Layout.createSequentialGroup()
                                .addGap(0, 32, Short.MAX_VALUE)
                                .addGroup(painelInternoMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medioCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(facilCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dificilCB))
                                .addGap(155, 155, 155)))
                        .addGroup(painelInternoMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logoutBT, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelInternoMenu2Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        painelInternoMenu2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {facilCB, imagemCB, medioCB, numberCB});

        painelInternoMenu2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {logoutBT, rankingBT, startButton});

        painelInternoMenu2Layout.setVerticalGroup(
            painelInternoMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInternoMenu2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(painelInternoMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelInternoMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(painelInternoMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facilCB)
                    .addComponent(imagemCB))
                .addGap(33, 33, 33)
                .addGroup(painelInternoMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberCB)
                    .addComponent(medioCB))
                .addGap(38, 38, 38)
                .addGroup(painelInternoMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dificilCB)
                    .addComponent(letterCB))
                .addGap(51, 51, 51)
                .addGroup(painelInternoMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rankingBT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        painelInternoMenu2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {facilCB, imagemCB, medioCB, numberCB});

        painelInternoMenu2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {logoutBT, rankingBT, startButton});

        painelInternoMenu2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel4});

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Production by:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Gustavo Moreira Lopes");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Dominique Kellen Esteves da Silva");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cauã Gomes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(painelInternoMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(painelInternoMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel7)
                .addGap(0, 0, 0)
                .addComponent(jLabel8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static boolean veriLetraEasy = false;
    public static boolean veriLetraMedium = false;
    public static boolean veriLetraHard = false;
    public static boolean veriNumberEasy = false;
    public static boolean veriNumberMedium = false;
    public static boolean veriNumberHard = false;
    public static boolean veriImageEasy = false;
    public static boolean veriImageMedium = false;
    public static boolean veriImageHard = false;
    //public static boolean termino = false;


    private void imagemCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagemCBActionPerformed
        imagemCB.setSelected(true);
        numberCB.setSelected(false);
        letterCB.setSelected(false);
    }//GEN-LAST:event_imagemCBActionPerformed

    private void numberCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberCBActionPerformed
        imagemCB.setSelected(false);
        numberCB.setSelected(true);
        letterCB.setSelected(false);
    }//GEN-LAST:event_numberCBActionPerformed

    private void facilCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facilCBActionPerformed
        facilCB.setSelected(true);
        medioCB.setSelected(false);
        dificilCB.setSelected(false);
    }//GEN-LAST:event_facilCBActionPerformed

    private void medioCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medioCBActionPerformed
        facilCB.setSelected(false);
        medioCB.setSelected(true);
        dificilCB.setSelected(false);
    }//GEN-LAST:event_medioCBActionPerformed

    private void letterCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterCBActionPerformed
        imagemCB.setSelected(false);
        numberCB.setSelected(false);
        letterCB.setSelected(true);
    }//GEN-LAST:event_letterCBActionPerformed

    private void dificilCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dificilCBActionPerformed
        facilCB.setSelected(false);
        medioCB.setSelected(false);
        dificilCB.setSelected(true);
    }//GEN-LAST:event_dificilCBActionPerformed

    private void imagemCBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_imagemCBKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (imagemCB.isSelected()) {
                if (facilCB.isSelected()) {
                    veriImageEasy = true;
                    new FormEasyImage().setVisible(true);
                }
            } else if (medioCB.isSelected()) {
                veriImageMedium = true;
                new FormMediumImage().setVisible(true);
            } else if (dificilCB.isSelected()) {
                veriImageHard = true;
                new FormHardImage().setVisible(true);
            }
        }
        imagemCB.setSelected(false);
        facilCB.setSelected(false);
        medioCB.setSelected(false);
        dificilCB.setSelected(false);

    }//GEN-LAST:event_imagemCBKeyPressed

    private void numberCBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberCBKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (numberCB.isSelected()) {
                if (facilCB.isSelected()) {
                    veriNumberEasy = true;
                    new FormEasyNumber().setVisible(true);
                } else if (medioCB.isSelected()) {
                    veriNumberMedium = true;
                    new FormMediumNumber().setVisible(true);
                } else if (dificilCB.isSelected()) {
                    veriNumberHard = true;
                    new FormHardNumber().setVisible(true);
                }

            }

        }
        numberCB.setSelected(false);
        facilCB.setSelected(false);
        medioCB.setSelected(false);
        dificilCB.setSelected(false);


    }//GEN-LAST:event_numberCBKeyPressed

    private void letterCBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letterCBKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (letterCB.isSelected()) {
                if (facilCB.isSelected()) {
                    veriLetraEasy = true;
                    new FormEasyLetter().setVisible(true);
                } else if (medioCB.isSelected()) {
                    veriLetraMedium = true;
                    new FormMediumLetter().setVisible(true);
                } else if (dificilCB.isSelected()) {
                    veriLetraHard = true;
                    new FormHardLetter().setVisible(true);
                }
            }

        }
        letterCB.setSelected(false);
        facilCB.setSelected(false);
        medioCB.setSelected(false);
        dificilCB.setSelected(false);

    }//GEN-LAST:event_letterCBKeyPressed

    private void facilCBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_facilCBKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (facilCB.isSelected()) {
                if (letterCB.isSelected()) {
                    veriLetraEasy = true;
                    new FormEasyLetter().setVisible(true);
                } else if (facilCB.isSelected()) {
                    if (imagemCB.isSelected()) {
                        veriImageEasy = true;
                        new FormEasyImage().setVisible(true);
                    }
                } else if (facilCB.isSelected()) {
                    if (numberCB.isSelected()) {
                        veriNumberEasy = true;
                        new FormEasyNumber().setVisible(true);
                    }
                }
            }
        }
        facilCB.setSelected(false);
        letterCB.setSelected(false);
        imagemCB.setSelected(false);
        numberCB.setSelected(false);


    }//GEN-LAST:event_facilCBKeyPressed

    private void medioCBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_medioCBKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (medioCB.isSelected()) {
                if (letterCB.isSelected()) {
                    veriLetraMedium = true;
                    new FormMediumLetter().setVisible(true);
                } else if (medioCB.isSelected()) {
                    if (imagemCB.isSelected()) {
                        veriImageMedium = true;
                        new FormMediumImage().setVisible(true);
                    }
                } else if (medioCB.isSelected()) {
                    if (numberCB.isSelected()) {
                        veriNumberMedium = true;
                        new FormMediumNumber().setVisible(true);
                    }
                }
            }
        }
        medioCB.setSelected(false);
        letterCB.setSelected(false);
        imagemCB.setSelected(false);
        numberCB.setSelected(false);

    }//GEN-LAST:event_medioCBKeyPressed

    private void dificilCBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dificilCBKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (dificilCB.isSelected()) {
                if (letterCB.isSelected()) {
                    veriLetraHard = true;
                    new FormHardLetter().setVisible(true);
                } else if (dificilCB.isSelected()) {
                    if (imagemCB.isSelected()) {
                        veriImageHard = true;
                        new FormHardImage().setVisible(true);
                    }
                } else if (dificilCB.isSelected()) {
                    if (numberCB.isSelected()) {
                        veriNumberHard = true;
                        new FormHardNumber().setVisible(true);
                    }
                }
            }
        }
        dificilCB.setSelected(false);
        letterCB.setSelected(false);
        imagemCB.setSelected(false);
        numberCB.setSelected(false);

    }//GEN-LAST:event_dificilCBKeyPressed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed

        if (imagemCB.isSelected()) {
            if (facilCB.isSelected()) {
                veriImageEasy = true;
                new FormEasyImage().setVisible(true);

            } else if (medioCB.isSelected()) {
                veriImageMedium = true;
                new FormMediumImage().setVisible(true);
            } else if (dificilCB.isSelected()) {
                veriImageHard = true;
                new FormHardImage().setVisible(true);
            }
        } else if (numberCB.isSelected()) {
            if (facilCB.isSelected()) {
                veriNumberEasy = true;
                new FormEasyNumber().setVisible(true);
            } else if (medioCB.isSelected()) {
                veriNumberMedium = true;
                new FormMediumNumber().setVisible(true);
            } else if (dificilCB.isSelected()) {
                veriNumberHard = true;
                new FormHardNumber().setVisible(true);
            }
        } else if (letterCB.isSelected()) {
            if (facilCB.isSelected()) {
                veriLetraEasy = true;
                new FormEasyLetter().setVisible(true);
            } else if (medioCB.isSelected()) {
                veriLetraMedium = true;
                new FormMediumLetter().setVisible(true);
            } else if (dificilCB.isSelected()) {
                veriLetraHard = true;
                new FormHardLetter().setVisible(true);
            }
        }

        imagemCB.setSelected(false);
        letterCB.setSelected(false);
        numberCB.setSelected(false);
        facilCB.setSelected(false);
        medioCB.setSelected(false);
        dificilCB.setSelected(false);


    }//GEN-LAST:event_startButtonActionPerformed

    private void logoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTActionPerformed
        dispose();
    }//GEN-LAST:event_logoutBTActionPerformed

    private void rankingBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankingBTActionPerformed
        formRanking.listar();
    }//GEN-LAST:event_rankingBTActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox dificilCB;
    private javax.swing.JCheckBox facilCB;
    private javax.swing.JCheckBox imagemCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JCheckBox letterCB;
    private javax.swing.JButton logoutBT;
    private javax.swing.JCheckBox medioCB;
    private javax.swing.JCheckBox numberCB;
    private javax.swing.JPanel painelInternoMenu2;
    private javax.swing.JButton rankingBT;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
