            /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quebracabeca;

import java.awt.event.KeyEvent;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author mathe
 */
public class FormMediumImage extends javax.swing.JFrame {

    int newX;
    int newY;
    private TimerTask timerTask;
    private Timer timer;

    /**
     * Creates new form NewJFrame
     */
    public FormMediumImage() {
        initComponents();
        timer = new Timer();
        timerTask = new Cronometro();
        timer.scheduleAtFixedRate(timerTask, 0, 1);

    }
    RankingDAO rankingDao = new RankingDAO();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelT1 = new javax.swing.JLabel();
        labelT2 = new javax.swing.JLabel();
        labelT3 = new javax.swing.JLabel();
        labelT4 = new javax.swing.JLabel();
        labelT5 = new javax.swing.JLabel();
        labelT6 = new javax.swing.JLabel();
        labelT7 = new javax.swing.JLabel();
        labelT8 = new javax.swing.JLabel();
        labelT9 = new javax.swing.JLabel();
        labelT10 = new javax.swing.JLabel();
        labelT11 = new javax.swing.JLabel();
        labelT12 = new javax.swing.JLabel();
        labelT13 = new javax.swing.JLabel();
        labelT14 = new javax.swing.JLabel();
        labelT15 = new javax.swing.JLabel();
        jEmpty = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelSegundos = new java.awt.Label();
        labelMiliseg = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        labelMinutos = new java.awt.Label();
        sairBTGatinhoMedio = new javax.swing.JButton();
        restartBTGatinhoMedio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        labelT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medium_difficult/2.png"))); // NOI18N
        labelT1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT1MouseClicked(evt);
            }
        });

        labelT2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medium_difficult/3.png"))); // NOI18N
        labelT2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT2MouseClicked(evt);
            }
        });

        labelT3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medium_difficult/10.png"))); // NOI18N
        labelT3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT3MouseClicked(evt);
            }
        });

        labelT4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medium_difficult/11.png"))); // NOI18N
        labelT4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT4MouseClicked(evt);
            }
        });

        labelT5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medium_difficult/14.png"))); // NOI18N
        labelT5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT5MouseClicked(evt);
            }
        });

        labelT6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medium_difficult/1.png"))); // NOI18N
        labelT6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT6MouseClicked(evt);
            }
        });

        labelT7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medium_difficult/13.png"))); // NOI18N
        labelT7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT7MouseClicked(evt);
            }
        });

        labelT8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medium_difficult/15.png"))); // NOI18N
        labelT8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT8MouseClicked(evt);
            }
        });

        labelT9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medium_difficult/5.png"))); // NOI18N
        labelT9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT9MouseClicked(evt);
            }
        });

        labelT10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medium_difficult/4.png"))); // NOI18N
        labelT10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT10MouseClicked(evt);
            }
        });

        labelT11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medium_difficult/8.png"))); // NOI18N
        labelT11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT11MouseClicked(evt);
            }
        });

        labelT12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medium_difficult/7.png"))); // NOI18N
        labelT12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT12MouseClicked(evt);
            }
        });

        labelT13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medium_difficult/6.png"))); // NOI18N
        labelT13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT13MouseClicked(evt);
            }
        });

        labelT14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medium_difficult/12.png"))); // NOI18N
        labelT14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT14MouseClicked(evt);
            }
        });

        labelT15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medium_difficult/9.png"))); // NOI18N
        labelT15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelT15MouseClicked(evt);
            }
        });

        jEmpty.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jEmpty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEmptyMouseClicked(evt);
            }
        });

        labelSegundos.setAlignment(1);
        labelSegundos.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        labelSegundos.setName(""); // NOI18N
        labelSegundos.setText("00");

        labelMiliseg.setAlignment(1);
        labelMiliseg.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelMiliseg.setText("000");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText(":");

        labelMinutos.setAlignment(1);
        labelMinutos.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        labelMinutos.setName(""); // NOI18N
        labelMinutos.setText("00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMinutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSegundos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMiliseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelMiliseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sairBTGatinhoMedio.setFont(new java.awt.Font("Press Start 2P", 0, 11)); // NOI18N
        sairBTGatinhoMedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontes/Programming-Delete-Sign-icon.png"))); // NOI18N
        sairBTGatinhoMedio.setText("Sair");
        sairBTGatinhoMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBTGatinhoMedioActionPerformed(evt);
            }
        });

        restartBTGatinhoMedio.setFont(new java.awt.Font("Press Start 2P", 0, 11)); // NOI18N
        restartBTGatinhoMedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontes/Very-Basic-Reload-icon.png"))); // NOI18N
        restartBTGatinhoMedio.setText("Restart");
        restartBTGatinhoMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartBTGatinhoMedioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelT5)
                        .addGap(0, 0, 0)
                        .addComponent(labelT6)
                        .addGap(0, 0, 0)
                        .addComponent(labelT7)
                        .addGap(0, 0, 0)
                        .addComponent(labelT8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelT1)
                        .addGap(0, 0, 0)
                        .addComponent(labelT2)
                        .addGap(0, 0, 0)
                        .addComponent(labelT3)
                        .addGap(0, 0, 0)
                        .addComponent(labelT4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelT9)
                                .addGap(0, 0, 0)
                                .addComponent(labelT10)
                                .addGap(0, 0, 0)
                                .addComponent(labelT11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelT13)
                                .addGap(0, 0, 0)
                                .addComponent(labelT14)
                                .addGap(0, 0, 0)
                                .addComponent(labelT15)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelT12)
                            .addComponent(jEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sairBTGatinhoMedio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(restartBTGatinhoMedio)))
                .addGap(0, 0, 0))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {restartBTGatinhoMedio, sairBTGatinhoMedio});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelT1)
                    .addComponent(labelT2)
                    .addComponent(labelT3)
                    .addComponent(labelT4))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelT6)
                    .addComponent(labelT5)
                    .addComponent(labelT7)
                    .addComponent(labelT8))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelT10)
                    .addComponent(labelT9)
                    .addComponent(labelT11)
                    .addComponent(labelT12))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelT14)
                    .addComponent(labelT13)
                    .addComponent(labelT15)
                    .addComponent(jEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sairBTGatinhoMedio)
                            .addComponent(restartBTGatinhoMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {restartBTGatinhoMedio, sairBTGatinhoMedio});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void setTextoCronometroSegundos(String texto) {
        labelSegundos.setText(texto);
    }

    public static void setTextoCronometroMinutos(String texto) {
        labelMinutos.setText(texto);
    }

    public static void setTextoCronometroMilisegundos(String texto) {
        labelMiliseg.setText(texto);
    }

    private void labelT6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT6MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT6.getX() + 125 + "," + labelT6.getY())) {
            newX = labelT6.getX() + 125;
            jEmpty.setBounds(labelT6.getX(), labelT6.getY(), 125, 125);
            labelT6.setBounds(newX, labelT6.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT6.getX() - 125 + "," + labelT6.getY())) {
            newX = labelT6.getX() - 125;
            jEmpty.setBounds(labelT6.getX(), labelT6.getY(), 125, 125);
            labelT6.setBounds(newX, labelT6.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT6.getX() + "," + (labelT6.getY() + 125))) {
            newY = labelT6.getY() + 125;
            jEmpty.setBounds(labelT6.getX(), labelT6.getY(), 125, 125);
            labelT6.setBounds(labelT6.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT6.getX() + "," + (labelT6.getY() - 125))) {
            newY = labelT6.getY() - 125;
            jEmpty.setBounds(labelT6.getX(), labelT6.getY(), 125, 125);
            labelT6.setBounds(labelT6.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT6MouseClicked

    private void labelT1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT1MouseClicked
        //direita empty
        if (getPos(jEmpty).equals(labelT1.getX() + 125 + "," + labelT1.getY())) {
            newX = labelT1.getX() + 125;
            jEmpty.setBounds(labelT1.getX(), labelT1.getY(), 125, 125);
            labelT1.setBounds(newX, labelT1.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT1.getX() - 125 + "," + labelT1.getY())) {
            newX = labelT1.getX() - 125;
            jEmpty.setBounds(labelT1.getX(), labelT1.getY(), 125, 125);
            labelT1.setBounds(newX, labelT1.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT1.getX() + "," + (labelT1.getY() + 125))) {
            newY = labelT1.getY() + 125;
            jEmpty.setBounds(labelT1.getX(), labelT1.getY(), 125, 125);
            labelT1.setBounds(labelT1.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT1.getX() + "," + (labelT1.getY() - 125))) {
            newY = labelT1.getY() - 125;
            jEmpty.setBounds(labelT1.getX(), labelT1.getY(), 125, 125);
            labelT1.setBounds(labelT1.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT1MouseClicked

    private void labelT2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT2MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT2.getX() + 125 + "," + labelT2.getY())) {
            newX = labelT2.getX() + 125;
            jEmpty.setBounds(labelT2.getX(), labelT2.getY(), 125, 125);
            labelT2.setBounds(newX, labelT2.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT2.getX() - 125 + "," + labelT2.getY())) {
            newX = labelT2.getX() - 125;
            jEmpty.setBounds(labelT2.getX(), labelT2.getY(), 125, 125);
            labelT2.setBounds(newX, labelT2.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT2.getX() + "," + (labelT2.getY() + 125))) {
            newY = labelT2.getY() + 125;
            jEmpty.setBounds(labelT2.getX(), labelT2.getY(), 125, 125);
            labelT2.setBounds(labelT2.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT2.getX() + "," + (labelT2.getY() - 125))) {
            newY = labelT2.getY() - 125;
            jEmpty.setBounds(labelT2.getX(), labelT2.getY(), 125, 125);
            labelT2.setBounds(labelT2.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT2MouseClicked

    private void labelT10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT10MouseClicked
        //direita empty
        if (getPos(jEmpty).equals(labelT10.getX() + 125 + "," + labelT10.getY())) {
            newX = labelT10.getX() + 125;
            jEmpty.setBounds(labelT10.getX(), labelT10.getY(), 125, 125);
            labelT10.setBounds(newX, labelT10.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT10.getX() - 125 + "," + labelT10.getY())) {
            newX = labelT10.getX() - 125;
            jEmpty.setBounds(labelT10.getX(), labelT10.getY(), 125, 125);
            labelT10.setBounds(newX, labelT10.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT10.getX() + "," + (labelT10.getY() + 125))) {
            newY = labelT10.getY() + 125;
            jEmpty.setBounds(labelT10.getX(), labelT10.getY(), 125, 125);
            labelT10.setBounds(labelT10.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT10.getX() + "," + (labelT10.getY() - 125))) {
            newY = labelT10.getY() - 125;
            jEmpty.setBounds(labelT10.getX(), labelT10.getY(), 125, 125);
            labelT10.setBounds(labelT10.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT10MouseClicked

    private void labelT9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT9MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT9.getX() + 125 + "," + labelT9.getY())) {
            newX = labelT9.getX() + 125;
            jEmpty.setBounds(labelT9.getX(), labelT9.getY(), 125, 125);
            labelT9.setBounds(newX, labelT9.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT9.getX() - 125 + "," + labelT9.getY())) {
            newX = labelT9.getX() - 125;
            jEmpty.setBounds(labelT9.getX(), labelT9.getY(), 125, 125);
            labelT9.setBounds(newX, labelT9.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT9.getX() + "," + (labelT9.getY() + 125))) {
            newY = labelT9.getY() + 125;
            jEmpty.setBounds(labelT9.getX(), labelT9.getY(), 125, 125);
            labelT9.setBounds(labelT9.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT9.getX() + "," + (labelT9.getY() - 125))) {
            newY = labelT9.getY() - 125;
            jEmpty.setBounds(labelT9.getX(), labelT9.getY(), 125, 125);
            labelT9.setBounds(labelT9.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT9MouseClicked

    private void labelT13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT13MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT13.getX() + 125 + "," + labelT13.getY())) {
            newX = labelT13.getX() + 125;
            jEmpty.setBounds(labelT13.getX(), labelT13.getY(), 125, 125);
            labelT13.setBounds(newX, labelT13.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT13.getX() - 125 + "," + labelT13.getY())) {
            newX = labelT13.getX() - 125;
            jEmpty.setBounds(labelT13.getX(), labelT13.getY(), 125, 125);
            labelT13.setBounds(newX, labelT13.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT13.getX() + "," + (labelT13.getY() + 125))) {
            newY = labelT13.getY() + 125;
            jEmpty.setBounds(labelT13.getX(), labelT13.getY(), 125, 125);
            labelT13.setBounds(labelT13.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT13.getX() + "," + (labelT13.getY() - 125))) {
            newY = labelT13.getY() - 125;
            jEmpty.setBounds(labelT13.getX(), labelT13.getY(), 125, 125);
            labelT13.setBounds(labelT13.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT13MouseClicked

    private void labelT12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT12MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT12.getX() + 125 + "," + labelT12.getY())) {
            newX = labelT12.getX() + 125;
            jEmpty.setBounds(labelT12.getX(), labelT12.getY(), 125, 125);
            labelT12.setBounds(newX, labelT12.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT12.getX() - 125 + "," + labelT12.getY())) {
            newX = labelT12.getX() - 125;
            jEmpty.setBounds(labelT12.getX(), labelT12.getY(), 125, 125);
            labelT12.setBounds(newX, labelT12.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT12.getX() + "," + (labelT12.getY() + 125))) {
            newY = labelT12.getY() + 125;
            jEmpty.setBounds(labelT12.getX(), labelT12.getY(), 125, 125);
            labelT12.setBounds(labelT12.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT12.getX() + "," + (labelT12.getY() - 125))) {
            newY = labelT12.getY() - 125;
            jEmpty.setBounds(labelT12.getX(), labelT12.getY(), 125, 125);
            labelT12.setBounds(labelT12.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT12MouseClicked

    private void labelT11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT11MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT11.getX() + 125 + "," + labelT11.getY())) {
            newX = labelT11.getX() + 125;
            jEmpty.setBounds(labelT11.getX(), labelT11.getY(), 125, 125);
            labelT11.setBounds(newX, labelT11.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT11.getX() - 125 + "," + labelT11.getY())) {
            newX = labelT11.getX() - 125;
            jEmpty.setBounds(labelT11.getX(), labelT11.getY(), 125, 125);
            labelT11.setBounds(newX, labelT11.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT11.getX() + "," + (labelT11.getY() + 125))) {
            newY = labelT11.getY() + 125;
            jEmpty.setBounds(labelT11.getX(), labelT11.getY(), 125, 125);
            labelT11.setBounds(labelT11.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT11.getX() + "," + (labelT11.getY() - 125))) {
            newY = labelT11.getY() - 125;
            jEmpty.setBounds(labelT11.getX(), labelT11.getY(), 125, 125);
            labelT11.setBounds(labelT11.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT11MouseClicked

    private void labelT15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT15MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT15.getX() + 125 + "," + labelT15.getY())) {
            newX = labelT15.getX() + 125;
            jEmpty.setBounds(labelT15.getX(), labelT15.getY(), 125, 125);
            labelT15.setBounds(newX, labelT15.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT15.getX() - 125 + "," + labelT15.getY())) {
            newX = labelT15.getX() - 125;
            jEmpty.setBounds(labelT15.getX(), labelT15.getY(), 125, 125);
            labelT15.setBounds(newX, labelT15.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT15.getX() + "," + (labelT15.getY() + 125))) {
            newY = labelT15.getY() + 125;
            jEmpty.setBounds(labelT15.getX(), labelT15.getY(), 125, 125);
            labelT15.setBounds(labelT15.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT15.getX() + "," + (labelT15.getY() - 125))) {
            newY = labelT15.getY() - 125;
            jEmpty.setBounds(labelT15.getX(), labelT15.getY(), 125, 125);
            labelT15.setBounds(labelT15.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT15MouseClicked

    private void labelT3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT3MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT3.getX() + 125 + "," + labelT3.getY())) {
            newX = labelT3.getX() + 125;
            jEmpty.setBounds(labelT3.getX(), labelT3.getY(), 125, 125);
            labelT3.setBounds(newX, labelT3.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT3.getX() - 125 + "," + labelT3.getY())) {
            newX = labelT3.getX() - 125;
            jEmpty.setBounds(labelT3.getX(), labelT3.getY(), 125, 125);
            labelT3.setBounds(newX, labelT3.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT3.getX() + "," + (labelT3.getY() + 125))) {
            newY = labelT3.getY() + 125;
            jEmpty.setBounds(labelT3.getX(), labelT3.getY(), 125, 125);
            labelT3.setBounds(labelT3.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT3.getX() + "," + (labelT3.getY() - 125))) {
            newY = labelT3.getY() - 125;
            jEmpty.setBounds(labelT3.getX(), labelT3.getY(), 125, 125);
            labelT3.setBounds(labelT3.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT3MouseClicked

    private void labelT4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT4MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT4.getX() + 125 + "," + labelT4.getY())) {
            newX = labelT4.getX() + 125;
            jEmpty.setBounds(labelT4.getX(), labelT4.getY(), 125, 125);
            labelT4.setBounds(newX, labelT4.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT4.getX() - 125 + "," + labelT4.getY())) {
            newX = labelT4.getX() - 125;
            jEmpty.setBounds(labelT4.getX(), labelT4.getY(), 125, 125);
            labelT4.setBounds(newX, labelT4.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT4.getX() + "," + (labelT4.getY() + 125))) {
            newY = labelT4.getY() + 125;
            jEmpty.setBounds(labelT4.getX(), labelT4.getY(), 125, 125);
            labelT4.setBounds(labelT4.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT4.getX() + "," + (labelT4.getY() - 125))) {
            newY = labelT4.getY() - 125;
            jEmpty.setBounds(labelT4.getX(), labelT4.getY(), 125, 125);
            labelT4.setBounds(labelT4.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT4MouseClicked

    private void labelT14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT14MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT14.getX() + 125 + "," + labelT14.getY())) {
            newX = labelT14.getX() + 125;
            jEmpty.setBounds(labelT14.getX(), labelT14.getY(), 125, 125);
            labelT14.setBounds(newX, labelT14.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT14.getX() - 125 + "," + labelT14.getY())) {
            newX = labelT14.getX() - 125;
            jEmpty.setBounds(labelT14.getX(), labelT14.getY(), 125, 125);
            labelT14.setBounds(newX, labelT14.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT14.getX() + "," + (labelT14.getY() + 125))) {
            newY = labelT14.getY() + 125;
            jEmpty.setBounds(labelT14.getX(), labelT14.getY(), 125, 125);
            labelT14.setBounds(labelT14.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT14.getX() + "," + (labelT14.getY() - 125))) {
            newY = labelT14.getY() - 125;
            jEmpty.setBounds(labelT14.getX(), labelT14.getY(), 125, 125);
            labelT14.setBounds(labelT14.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT14MouseClicked

    private void labelT7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT7MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT7.getX() + 125 + "," + labelT7.getY())) {
            newX = labelT7.getX() + 125;
            jEmpty.setBounds(labelT7.getX(), labelT7.getY(), 125, 125);
            labelT7.setBounds(newX, labelT7.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT7.getX() - 125 + "," + labelT7.getY())) {
            newX = labelT7.getX() - 125;
            jEmpty.setBounds(labelT7.getX(), labelT7.getY(), 125, 125);
            labelT7.setBounds(newX, labelT7.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT7.getX() + "," + (labelT7.getY() + 125))) {
            newY = labelT7.getY() + 125;
            jEmpty.setBounds(labelT7.getX(), labelT7.getY(), 125, 125);
            labelT7.setBounds(labelT7.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT7.getX() + "," + (labelT7.getY() - 125))) {
            newY = labelT7.getY() - 125;
            jEmpty.setBounds(labelT7.getX(), labelT7.getY(), 125, 125);
            labelT7.setBounds(labelT7.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT7MouseClicked

    private void labelT5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT5MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT5.getX() + 125 + "," + labelT5.getY())) {
            newX = labelT5.getX() + 125;
            jEmpty.setBounds(labelT5.getX(), labelT5.getY(), 125, 125);
            labelT5.setBounds(newX, labelT5.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT5.getX() - 125 + "," + labelT5.getY())) {
            newX = labelT5.getX() - 125;
            jEmpty.setBounds(labelT5.getX(), labelT5.getY(), 125, 125);
            labelT5.setBounds(newX, labelT5.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT5.getX() + "," + (labelT5.getY() + 125))) {
            newY = labelT5.getY() + 125;
            jEmpty.setBounds(labelT5.getX(), labelT5.getY(), 125, 125);
            labelT5.setBounds(labelT5.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT5.getX() + "," + (labelT5.getY() - 125))) {
            newY = labelT5.getY() - 125;
            jEmpty.setBounds(labelT5.getX(), labelT5.getY(), 125, 125);
            labelT5.setBounds(labelT5.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT5MouseClicked

    private void labelT8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelT8MouseClicked

        //direita empty
        if (getPos(jEmpty).equals(labelT8.getX() + 125 + "," + labelT8.getY())) {
            newX = labelT8.getX() + 125;
            jEmpty.setBounds(labelT8.getX(), labelT8.getY(), 125, 125);
            labelT8.setBounds(newX, labelT8.getY(), 125, 125);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelT8.getX() - 125 + "," + labelT8.getY())) {
            newX = labelT8.getX() - 125;
            jEmpty.setBounds(labelT8.getX(), labelT8.getY(), 125, 125);
            labelT8.setBounds(newX, labelT8.getY(), 125, 125);
        } //subir empty
        else if (getPos(jEmpty).equals(labelT8.getX() + "," + (labelT8.getY() + 125))) {
            newY = labelT8.getY() + 125;
            jEmpty.setBounds(labelT8.getX(), labelT8.getY(), 125, 125);
            labelT8.setBounds(labelT8.getX(), newY, 125, 125);
        } //descer empty
        else if (getPos(jEmpty).equals(labelT8.getX() + "," + (labelT8.getY() - 125))) {
            newY = labelT8.getY() - 125;
            jEmpty.setBounds(labelT8.getX(), labelT8.getY(), 125, 125);
            labelT8.setBounds(labelT8.getX(), newY, 125, 125);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelT8MouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void jEmptyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEmptyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmptyMouseClicked

    private void sairBTGatinhoMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBTGatinhoMedioActionPerformed
        dispose();
        timer.cancel();
    }//GEN-LAST:event_sairBTGatinhoMedioActionPerformed

    private void restartBTGatinhoMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartBTGatinhoMedioActionPerformed

        labelT1.setBounds(0, 0, 125, 125);
        labelT2.setBounds(125, 0, 125, 125);
        labelT3.setBounds(250, 0, 125, 125);
        labelT4.setBounds(375, 0, 125, 125);

        labelT5.setBounds(0, 125, 125, 125);
        labelT6.setBounds(125, 125, 125, 125);
        labelT7.setBounds(250, 125, 125, 125);
        labelT8.setBounds(375, 125, 125, 125);

        labelT9.setBounds(0, 250, 125, 125);
        labelT10.setBounds(125, 250, 125, 125);
        labelT11.setBounds(250, 250, 125, 125);
        labelT12.setBounds(375, 250, 125, 125);

        labelT13.setBounds(0, 375, 125, 125);
        labelT14.setBounds(125, 375, 125, 125);
        labelT15.setBounds(250, 375, 125, 125);
        
        jEmpty.setBounds(375, 375, 125, 125);

        timer.cancel();
        labelMiliseg.setText("000");
        labelMinutos.setText("00");
        labelSegundos.setText("00");
        timer = new Timer();
        timerTask = new Cronometro();
        timer.scheduleAtFixedRate(timerTask, 0, 1);

    }//GEN-LAST:event_restartBTGatinhoMedioActionPerformed

    public String getPos(JLabel label) {
        String pos = label.getX() + "," + label.getY();
        return pos;
    }

    public boolean winCondition() {

        if (getPos(labelT6).equals("0,0")
                && getPos(labelT1).equals("125,0")
                && getPos(labelT2).equals("250,0")
                && getPos(labelT10).equals("375,0")
                && getPos(labelT9).equals("0,125")
                && getPos(labelT13).equals("125,125")
                && getPos(labelT12).equals("250,125")
                && getPos(labelT11).equals("375,125")
                && getPos(labelT15).equals("0,250")
                && getPos(labelT3).equals("125,250")
                && getPos(labelT4).equals("250,250")
                && getPos(labelT14).equals("375,250")
                && getPos(labelT7).equals("0,375")
                && getPos(labelT5).equals("125,375")
                && getPos(labelT8).equals("250,375")) {

            timer.cancel();
            rankingDao.imagemMedium();

            return true;
        }

        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jEmpty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private static java.awt.Label labelMiliseg;
    private static java.awt.Label labelMinutos;
    private static java.awt.Label labelSegundos;
    private javax.swing.JLabel labelT1;
    private javax.swing.JLabel labelT10;
    private javax.swing.JLabel labelT11;
    private javax.swing.JLabel labelT12;
    private javax.swing.JLabel labelT13;
    private javax.swing.JLabel labelT14;
    private javax.swing.JLabel labelT15;
    private javax.swing.JLabel labelT2;
    private javax.swing.JLabel labelT3;
    private javax.swing.JLabel labelT4;
    private javax.swing.JLabel labelT5;
    private javax.swing.JLabel labelT6;
    private javax.swing.JLabel labelT7;
    private javax.swing.JLabel labelT8;
    private javax.swing.JLabel labelT9;
    private javax.swing.JButton restartBTGatinhoMedio;
    private javax.swing.JButton sairBTGatinhoMedio;
    // End of variables declaration//GEN-END:variables

}
