 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quebracabeca;

import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author IFPR
 */
public class FormEasyLetter extends javax.swing.JFrame {

    int newX;
    int newY;
    private Timer timer;
    private TimerTask timerTask;

    /**
     * Creates new form FormEasyLetra
     */
    public FormEasyLetter() {
        initComponents();

        timer = new Timer();
        timerTask = new Cronometro();
        timer.scheduleAtFixedRate(timerTask, 0, 1);

    }

    RankingDAO rankingDao = new RankingDAO();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelL3 = new javax.swing.JLabel();
        labelL1 = new javax.swing.JLabel();
        labelL8 = new javax.swing.JLabel();
        labelL6 = new javax.swing.JLabel();
        labelL5 = new javax.swing.JLabel();
        labelL4 = new javax.swing.JLabel();
        labelL7 = new javax.swing.JLabel();
        labelL2 = new javax.swing.JLabel();
        jEmpty = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelSegundos = new java.awt.Label();
        labelMiliseg = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        labelMinutos = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        restartLetraFacilBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelL3.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelL3.setText("A");
        labelL3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelL3MouseClicked(evt);
            }
        });

        labelL1.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelL1.setText("B");
        labelL1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelL1MouseClicked(evt);
            }
        });

        labelL8.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelL8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelL8.setText("C");
        labelL8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelL8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelL8MouseClicked(evt);
            }
        });

        labelL6.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelL6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelL6.setText("D");
        labelL6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelL6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelL6MouseClicked(evt);
            }
        });

        labelL5.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelL5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelL5.setText("E");
        labelL5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelL5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelL5MouseClicked(evt);
            }
        });

        labelL4.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelL4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelL4.setText("F");
        labelL4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelL4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelL4MouseClicked(evt);
            }
        });

        labelL7.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelL7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelL7.setText("G");
        labelL7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelL7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelL7MouseClicked(evt);
            }
        });

        labelL2.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        labelL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelL2.setText("H");
        labelL2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelL2MouseClicked(evt);
            }
        });

        jEmpty.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelSegundos.setAlignment(java.awt.Label.CENTER);
        labelSegundos.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        labelSegundos.setName(""); // NOI18N
        labelSegundos.setText("00");

        labelMiliseg.setAlignment(java.awt.Label.CENTER);
        labelMiliseg.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelMiliseg.setText("000");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText(":");

        labelMinutos.setAlignment(java.awt.Label.CENTER);
        labelMinutos.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        labelMinutos.setName(""); // NOI18N
        labelMinutos.setText("00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMinutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSegundos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMiliseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelMiliseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Press Start 2P", 0, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontes/Programming-Delete-Sign-icon.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        restartLetraFacilBT.setFont(new java.awt.Font("Press Start 2P", 0, 11)); // NOI18N
        restartLetraFacilBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fontes/Very-Basic-Reload-icon.png"))); // NOI18N
        restartLetraFacilBT.setText("Restart");
        restartLetraFacilBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartLetraFacilBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelL1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(labelL2)
                        .addGap(0, 0, 0)
                        .addComponent(labelL3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelL4)
                        .addGap(0, 0, 0)
                        .addComponent(labelL5)
                        .addGap(0, 0, 0)
                        .addComponent(labelL6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelL7)
                        .addGap(0, 0, 0)
                        .addComponent(labelL8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(restartLetraFacilBT)))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jEmpty, labelL1, labelL2, labelL3, labelL4, labelL5, labelL6, labelL7, labelL8});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, restartLetraFacilBT});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelL3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelL2)
                    .addComponent(labelL1))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelL4)
                    .addComponent(labelL5)
                    .addComponent(labelL6))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelL7)
                        .addComponent(labelL8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jEmpty))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(restartLetraFacilBT)
                            .addComponent(jButton1))
                        .addGap(22, 22, 22))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jEmpty, labelL1, labelL2, labelL3, labelL4, labelL5, labelL6, labelL7, labelL8});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, restartLetraFacilBT});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void setTextoCronometroSegundos(String texto) {
        labelSegundos.setText(texto);
    }

    public static void setTextoCronometroMinutos(String texto) {
        labelMinutos.setText(texto);
    }

    public static void setTextoCronometroMilisegundos(String texto) {
        labelMiliseg.setText(texto);
    }

    private void labelL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelL1MouseClicked
        // TODO add your handling code here:

        //direita empty
        if (getPos(jEmpty).equals(labelL1.getX() + 167 + "," + labelL1.getY())) {
            newX = labelL1.getX() + 167;
            jEmpty.setBounds(labelL1.getX(), labelL1.getY(), 167, 167);
            labelL1.setBounds(newX, labelL1.getY(), 167, 167);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelL1.getX() - 167 + "," + labelL1.getY())) {
            newX = labelL1.getX() - 167;
            jEmpty.setBounds(labelL1.getX(), labelL1.getY(), 167, 167);
            labelL1.setBounds(newX, labelL1.getY(), 167, 167);
        } //subir empty
        else if (getPos(jEmpty).equals(labelL1.getX() + "," + (labelL1.getY() + 167))) {
            newY = labelL1.getY() + 167;
            jEmpty.setBounds(labelL1.getX(), labelL1.getY(), 167, 167);
            labelL1.setBounds(labelL1.getX(), newY, 167, 167);
        } //descer empty
        else if (getPos(jEmpty).equals(labelL1.getX() + "," + (labelL1.getY() - 167))) {
            newY = labelL1.getY() - 167;
            jEmpty.setBounds(labelL1.getX(), labelL1.getY(), 167, 167);
            labelL1.setBounds(labelL1.getX(), newY, 167, 167);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }


    }//GEN-LAST:event_labelL1MouseClicked

    private void labelL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelL2MouseClicked
        // TODO add your handling code here:

        //direita empty
        if (getPos(jEmpty).equals(labelL2.getX() + 167 + "," + labelL2.getY())) {
            newX = labelL2.getX() + 167;
            jEmpty.setBounds(labelL2.getX(), labelL2.getY(), 167, 167);
            labelL2.setBounds(newX, labelL2.getY(), 167, 167);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelL2.getX() - 167 + "," + labelL2.getY())) {
            newX = labelL2.getX() - 167;
            jEmpty.setBounds(labelL2.getX(), labelL2.getY(), 167, 167);
            labelL2.setBounds(newX, labelL2.getY(), 167, 167);
        } //subir empty
        else if (getPos(jEmpty).equals(labelL2.getX() + "," + (labelL2.getY() + 167))) {
            newY = labelL2.getY() + 167;
            jEmpty.setBounds(labelL2.getX(), labelL2.getY(), 167, 167);
            labelL2.setBounds(labelL2.getX(), newY, 167, 167);
        } //descer empty
        else if (getPos(jEmpty).equals(labelL2.getX() + "," + (labelL2.getY() - 167))) {
            newY = labelL2.getY() - 167;
            jEmpty.setBounds(labelL2.getX(), labelL2.getY(), 167, 167);
            labelL2.setBounds(labelL2.getX(), newY, 167, 167);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }


    }//GEN-LAST:event_labelL2MouseClicked

    private void labelL3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelL3MouseClicked
        // TODO add your handling code here:

        //direita empty
        if (getPos(jEmpty).equals(labelL3.getX() + 167 + "," + labelL3.getY())) {
            newX = labelL3.getX() + 167;
            jEmpty.setBounds(labelL3.getX(), labelL3.getY(), 167, 167);
            labelL3.setBounds(newX, labelL3.getY(), 167, 167);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelL3.getX() - 167 + "," + labelL3.getY())) {
            newX = labelL3.getX() - 167;
            jEmpty.setBounds(labelL3.getX(), labelL3.getY(), 167, 167);
            labelL3.setBounds(newX, labelL3.getY(), 167, 167);
        } //subir empty
        else if (getPos(jEmpty).equals(labelL3.getX() + "," + (labelL3.getY() + 167))) {
            newY = labelL3.getY() + 167;
            jEmpty.setBounds(labelL3.getX(), labelL3.getY(), 167, 167);
            labelL3.setBounds(labelL3.getX(), newY, 167, 167);
        } //descer empty
        else if (getPos(jEmpty).equals(labelL3.getX() + "," + (labelL3.getY() - 167))) {
            newY = labelL3.getY() - 167;
            jEmpty.setBounds(labelL3.getX(), labelL3.getY(), 167, 167);
            labelL3.setBounds(labelL3.getX(), newY, 167, 167);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }


    }//GEN-LAST:event_labelL3MouseClicked

    private void labelL4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelL4MouseClicked
        // TODO add your handling code here:

        //direita empty
        if (getPos(jEmpty).equals(labelL4.getX() + 167 + "," + labelL4.getY())) {
            newX = labelL4.getX() + 167;
            jEmpty.setBounds(labelL4.getX(), labelL4.getY(), 167, 167);
            labelL4.setBounds(newX, labelL4.getY(), 167, 167);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelL4.getX() - 167 + "," + labelL4.getY())) {
            newX = labelL4.getX() - 167;
            jEmpty.setBounds(labelL4.getX(), labelL4.getY(), 167, 167);
            labelL4.setBounds(newX, labelL4.getY(), 167, 167);
        } //subir empty
        else if (getPos(jEmpty).equals(labelL4.getX() + "," + (labelL4.getY() + 167))) {
            newY = labelL4.getY() + 167;
            jEmpty.setBounds(labelL4.getX(), labelL4.getY(), 167, 167);
            labelL4.setBounds(labelL4.getX(), newY, 167, 167);
        } //descer empty
        else if (getPos(jEmpty).equals(labelL4.getX() + "," + (labelL4.getY() - 167))) {
            newY = labelL4.getY() - 167;
            jEmpty.setBounds(labelL4.getX(), labelL4.getY(), 167, 167);
            labelL4.setBounds(labelL4.getX(), newY, 167, 167);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }

    }//GEN-LAST:event_labelL4MouseClicked

    private void labelL5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelL5MouseClicked
        // TODO add your handling code here:
        //direita empty
        if (getPos(jEmpty).equals(labelL5.getX() + 167 + "," + labelL5.getY())) {
            newX = labelL5.getX() + 167;
            jEmpty.setBounds(labelL5.getX(), labelL5.getY(), 167, 167);
            labelL5.setBounds(newX, labelL5.getY(), 167, 167);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelL5.getX() - 167 + "," + labelL5.getY())) {
            newX = labelL5.getX() - 167;
            jEmpty.setBounds(labelL5.getX(), labelL5.getY(), 167, 167);
            labelL5.setBounds(newX, labelL5.getY(), 167, 167);
        } //subir empty
        else if (getPos(jEmpty).equals(labelL5.getX() + "," + (labelL5.getY() + 167))) {
            newY = labelL5.getY() + 167;
            jEmpty.setBounds(labelL5.getX(), labelL5.getY(), 167, 167);
            labelL5.setBounds(labelL5.getX(), newY, 167, 167);
        } //descer empty
        else if (getPos(jEmpty).equals(labelL5.getX() + "," + (labelL5.getY() - 167))) {
            newY = labelL5.getY() - 167;
            jEmpty.setBounds(labelL5.getX(), labelL5.getY(), 167, 167);
            labelL5.setBounds(labelL5.getX(), newY, 167, 167);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelL5MouseClicked

    private void labelL6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelL6MouseClicked
        // TODO add your handling code here:

        //direita empty
        if (getPos(jEmpty).equals(labelL6.getX() + 167 + "," + labelL6.getY())) {
            newX = labelL6.getX() + 167;
            jEmpty.setBounds(labelL6.getX(), labelL6.getY(), 167, 167);
            labelL6.setBounds(newX, labelL6.getY(), 167, 167);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelL6.getX() - 167 + "," + labelL6.getY())) {
            newX = labelL6.getX() - 167;
            jEmpty.setBounds(labelL6.getX(), labelL6.getY(), 167, 167);
            labelL6.setBounds(newX, labelL6.getY(), 167, 167);
        } //subir empty
        else if (getPos(jEmpty).equals(labelL6.getX() + "," + (labelL6.getY() + 167))) {
            newY = labelL6.getY() + 167;
            jEmpty.setBounds(labelL6.getX(), labelL6.getY(), 167, 167);
            labelL6.setBounds(labelL6.getX(), newY, 167, 167);
        } //descer empty
        else if (getPos(jEmpty).equals(labelL6.getX() + "," + (labelL6.getY() - 167))) {
            newY = labelL6.getY() - 167;
            jEmpty.setBounds(labelL6.getX(), labelL6.getY(), 167, 167);
            labelL6.setBounds(labelL6.getX(), newY, 167, 167);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }

    }//GEN-LAST:event_labelL6MouseClicked

    private void labelL7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelL7MouseClicked
        // TODO add your handling code here:

        //direita empty
        if (getPos(jEmpty).equals(labelL7.getX() + 167 + "," + labelL7.getY())) {
            newX = labelL7.getX() + 167;
            jEmpty.setBounds(labelL7.getX(), labelL7.getY(), 167, 167);
            labelL7.setBounds(newX, labelL7.getY(), 167, 167);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelL7.getX() - 167 + "," + labelL7.getY())) {
            newX = labelL7.getX() - 167;
            jEmpty.setBounds(labelL7.getX(), labelL7.getY(), 167, 167);
            labelL7.setBounds(newX, labelL7.getY(), 167, 167);
        } //subir empty
        else if (getPos(jEmpty).equals(labelL7.getX() + "," + (labelL7.getY() + 167))) {
            newY = labelL7.getY() + 167;
            jEmpty.setBounds(labelL7.getX(), labelL7.getY(), 167, 167);
            labelL7.setBounds(labelL7.getX(), newY, 167, 167);
        } //descer empty
        else if (getPos(jEmpty).equals(labelL7.getX() + "," + (labelL7.getY() - 167))) {
            newY = labelL7.getY() - 167;
            jEmpty.setBounds(labelL7.getX(), labelL7.getY(), 167, 167);
            labelL7.setBounds(labelL7.getX(), newY, 167, 167);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }

    }//GEN-LAST:event_labelL7MouseClicked

    private void labelL8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelL8MouseClicked
        // TODO add your handling code here:

        //direita empty
        if (getPos(jEmpty).equals(labelL8.getX() + 167 + "," + labelL8.getY())) {
            newX = labelL8.getX() + 167;
            jEmpty.setBounds(labelL8.getX(), labelL8.getY(), 167, 167);
            labelL8.setBounds(newX, labelL8.getY(), 167, 167);
        } //esquerda empty
        else if (getPos(jEmpty).equals(labelL8.getX() - 167 + "," + labelL8.getY())) {
            newX = labelL8.getX() - 167;
            jEmpty.setBounds(labelL8.getX(), labelL8.getY(), 167, 167);
            labelL8.setBounds(newX, labelL8.getY(), 167, 167);
        } //subir empty
        else if (getPos(jEmpty).equals(labelL8.getX() + "," + (labelL8.getY() + 167))) {
            newY = labelL8.getY() + 167;
            jEmpty.setBounds(labelL8.getX(), labelL8.getY(), 167, 167);
            labelL8.setBounds(labelL8.getX(), newY, 167, 167);
        } //descer empty
        else if (getPos(jEmpty).equals(labelL8.getX() + "," + (labelL8.getY() - 167))) {
            newY = labelL8.getY() - 167;
            jEmpty.setBounds(labelL8.getX(), labelL8.getY(), 167, 167);
            labelL8.setBounds(labelL8.getX(), newY, 167, 167);
        }
        if (winCondition()) {
            JOptionPane.showMessageDialog(null, "Parabéns, Você venceu!!!");
            this.dispose();
        }
    }//GEN-LAST:event_labelL8MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void restartLetraFacilBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartLetraFacilBTActionPerformed
        labelL1.setBounds(0, 0, 167, 167);
        labelL2.setBounds(167, 0, 167, 167);
        labelL3.setBounds(334, 0, 167, 167);

        labelL4.setBounds(0, 167, 167, 167);
        labelL5.setBounds(167, 167, 167, 167);
        labelL6.setBounds(334, 167, 167, 167);

        labelL7.setBounds(0, 334, 167, 167);
        labelL8.setBounds(167, 334, 167, 167);
        jEmpty.setBounds(334, 334, 167, 167);

        labelMiliseg.setText("000");
        labelMinutos.setText("00");
        labelSegundos.setText("00");
        
        
        timer.cancel();

        timer = new Timer();
        timerTask = new Cronometro();
        timer.scheduleAtFixedRate(timerTask, 0, 1);
    }//GEN-LAST:event_restartLetraFacilBTActionPerformed

    public String getPos(JLabel label) {
        String pos = label.getX() + "," + label.getY();
        return pos;
    }

    public boolean winCondition() {

        if (getPos(labelL3).equals("0,0")
                && getPos(labelL1).equals("167,0")
                && getPos(labelL8).equals("334,0")
                && getPos(labelL6).equals("0,167")
                && getPos(labelL5).equals("167,167")
                && getPos(labelL4).equals("334,167")
                && getPos(labelL7).equals("0,334")
                && getPos(labelL2).equals("167,334")) {
            timer.cancel();

            rankingDao.letraEasy();

            return true;
        }

        return false;
    }

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jEmpty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelL1;
    private javax.swing.JLabel labelL2;
    private javax.swing.JLabel labelL3;
    private javax.swing.JLabel labelL4;
    private javax.swing.JLabel labelL5;
    private javax.swing.JLabel labelL6;
    private javax.swing.JLabel labelL7;
    private javax.swing.JLabel labelL8;
    private static java.awt.Label labelMiliseg;
    private static java.awt.Label labelMinutos;
    private static java.awt.Label labelSegundos;
    private javax.swing.JButton restartLetraFacilBT;
    // End of variables declaration//GEN-END:variables
}
